/*
    EventReceiver.h - PogoBijoux Event Receiver


    ------------------------------------
    Copyright (c) 2021-2023 MCL Software
    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef EVENT_RECEIVER_H
#define EVENT_RECEIVER_H

class EventReceiver : public irr::IEventReceiver
{
    public:
        virtual bool OnEvent(const irr::SEvent& event)
        {
            if(event.EventType == irr::EET_KEY_INPUT_EVENT)
            {
                keyIsDown[event.KeyInput.Key] = event.KeyInput.PressedDown;
            }

            else if(event.EventType == irr::EET_MOUSE_INPUT_EVENT)
            {
                if(event.MouseInput.Event == irr::EMIE_LMOUSE_PRESSED_DOWN)
                {
                    mouseIsDown = true;
                }

                else if(event.MouseInput.Event == irr::EMIE_LMOUSE_LEFT_UP)
                {
                    mouseIsDown = false;
                }
            }

            return false;
        }

        virtual bool isKeyDown(irr::EKEY_CODE keyCode) const
        {
            return keyIsDown[keyCode];
        }

        virtual bool isMouseDown()
        {
            return mouseIsDown;
        }

        EventReceiver()
        {
            for(irr::u32 i = 0; i < irr::KEY_KEY_CODES_COUNT; i++)
            {
                keyIsDown[i] = false;
            }
        }

    private:
        bool mouseIsDown;
        bool keyIsDown[irr::KEY_KEY_CODES_COUNT];
};
#endif
